### ISSUE TITLE
Add compatibility with MacOS

### ISSUE THREAD

**Issue by sycured** [Diolinux/PhotoGIMP#4]
Is it possible to have a compatibility with MacOS?

**Comment by vinaysb** [comment]
I was able to install it on MacOS

**Comment by Diolinux** [comment]
> Is it possible to have a compatibility with MacOS?

Hi, actually, i guessing it already is compatibly, as @vinaysb said. Is just the default files from the GIMP's directory. I not really sure where macOS keep GIMP's files, but, you just have to override it with the content you find on this directory:

**.var/app/org.gimp.GIMP/config/GIMP/2.10**

This should work properly, but the custom icon is most likely to not work, but, is just a .png file, you may be able to customize the application icon manually. :)

If anyone that you know has knowledge about macOS packing, it would be nice to enable users to install a GIMP version with this patch pre-installed with .dmg file or something like that.

Best Regards

**Comment by vinaysb** [comment]
Yes as @Diolinux says it is compatible with macOS, it just takes a bit more work than FlatPaks as the config folder on macOS is stored at "/Users/<user>/Library/Application Support/GIMP/<version>". The way you do it is, 

0. Backup the config folder to somewhere safe.
1. Download the latest release and copy everything from ".var/app/org.gimp.GIMP/config/GIMP/<version>" from the release to the config folder and overwrite the existing files.
2. Now if you open GIMP, it should open the splash screen.

(OPTIONAL)

3. If you want to change the icon of GIMP, it is very easy, open the png file in the ".icons" folder in the downloaded release and select the entire image and copy it. Then from finder go to "applications", right-click on "gimp" and click on "get info". Then click on the gimp icon on the top and paste the image you copied.

4. If the gimp is looking kind-of funky when you open it and you cannot see the scrollbar, you will need to edit the gimprc in the config folder

**Comment by sycured** [comment]
Thank you, I'll try it today

**Comment by danicotillas** [comment]
> Yes as @Diolinux says it is compatible with macOS, it just takes a bit more work than FlatPaks as the config folder on macOS is stored at "/Users//Library/Application Support/GIMP/". The way you do it is,
> 
>     1. Backup the config folder to somewhere safe.
> 
>     2. Download the latest release and copy everything from ".var/app/org.gimp.GIMP/config/GIMP/" from the release to the config folder and overwrite the existing files.
> 
>     3. Now if you open GIMP, it should open the splash screen.
> 
> 
> (OPTIONAL)
> 
>     1. If you want to change the icon of GIMP, it is very easy, open the png file in the ".icons" folder in the downloaded release and select the entire image and copy it. Then from finder go to "applications", right-click on "gimp" and click on "get info". Then click on the gimp icon on the top and paste the image you copied.
> 
>     2. If the gimp is looking kind-of funky when you open it and you cannot see the scrollbar, you will need to edit the gimprc in the config folder

Hi,
I can´t find that config folder you are mentioning. I paste a screenshot to show you.
I just copy the folders on the download there.

![Captura de pantalla 2020-06-23 17 57 26](https://user-images.githubusercontent.com/7635775/85426739-284d9780-b57b-11ea-982d-4da6dbb3d3e6.png)

Thanks for the help!

**Comment by Diolinux** [comment]
Hey @danicotillas try to copy the all the files inside .var/app/org.gimp.GIMP/config/GIMP/2.10 to your gimp 2.10 folder (this on the screenshot), overwriting everything.

**Comment by danicotillas** [comment]
> Hey @danicotillas try to copy the all the files inside .var/app/org.gimp.GIMP/config/GIMP/2.10 to your gimp 2.10 folder (this on the screenshot), overwriting everything.

Thanks! I think it worked, except for the icons on the left bar. They aren´t like in [this picture](https://i2.wp.com/itsfoss.com/wp-content/uploads/2020/06/photogimp-editor-interface.jpg?resize=800%2C538&ssl=1) I saw from [this post](https://itsfoss.com/photogimp/).

This is my result:
![Captura de pantalla 2020-06-23 19 51 44](https://user-images.githubusercontent.com/7635775/85437618-2ee40b00-b58b-11ea-9ed2-207f5abbc640.png)

**Comment by vinaysb** [comment]
> I can´t find that config folder you are mentioning. I paste a screenshot to show you.
> I just copy the folders on the download there.

Yes, I made a mistake with markdown while typing the comment, I have fixed that now. But as already pointed out by @Diolinux its inside the 2.10 folder.

**Comment by Diolinux** [comment]
@danicotillas hi, try to copy your folder 2.10 folder and rename it to something like "2.10-bkp", then, delete all the content on the original 2.10 folder and copy the files from .var/app/org.gimp.GIMP/config/GIMP/2.10 inside it. That should do the trick.
If something goes wrong, you can just delete the 2.10 folder and rename 2.10-bkp to its original name.

**Comment by danicotillas** [comment]
> @danicotillas hi, try to copy your folder 2.10 folder and rename it to something like "2.10-bkp", then, delete all the content on the original 2.10 folder and copy the files from .var/app/org.gimp.GIMP/config/GIMP/2.10 inside it. That should do the trick.
> If something goes wrong, you can just delete the 2.10 folder and rename 2.10-bkp to its original name.

Still the same :(

![Captura de pantalla 2020-06-23 21 41 53](https://user-images.githubusercontent.com/7635775/85451656-66a67f00-b59a-11ea-8d2b-a096d5090e48.png)

**Comment by sudo-give-me-coffee** [comment]
> > Hey @danicotillas try to copy the all the files inside .var/app/org.gimp.GIMP/config/GIMP/2.10 to your gimp 2.10 folder (this on the screenshot), overwriting everything.
> 
> Thanks! I think it worked, except for the icons on the left bar. They aren´t like in [this picture](https://i2.wp.com/itsfoss.com/wp-content/uploads/2020/06/photogimp-editor-interface.jpg?resize=800%2C538&ssl=1) I saw from [this post](https://itsfoss.com/photogimp/).
> 
> This is my result:
> ![Captura de pantalla 2020-06-23 19 51 44](https://user-images.githubusercontent.com/7635775/85437618-2ee40b00-b58b-11ea-9ed2-207f5abbc640.png)

Which version os GIMP you is using? This feature comes with 2.10.15 on linux AppImage and 2.10.18 on other systems and formats... so you need it

**Comment by danicotillas** [comment]
That´s it @sudo-give-me-coffee ! I´m on 2.10.12 and for MacOS there is only to 2.10.14 so I´ll wait.
Thanks!

**Comment by Diolinux** [comment]
Video tutorial for macOS: https://youtu.be/5nXhtaGQs9U
